"use client";

import { useState } from "react";
import { FileText, Copy, Check, Stethoscope, Activity, ClipboardList, Calendar, Printer } from "lucide-react";
import { SOAPNote, PatientData, QualityScore } from "@/lib/agent/state";

interface SOAPPreviewProps {
  soapNote: SOAPNote | null;
  patientData?: PatientData | null;
  qualityScore?: QualityScore | null;
  cleanedTranscript?: string;
}

function QualityMeter({ score }: { score: QualityScore }) {
  const dims = [
    { label: "Completeness", value: score.completeness, color: "var(--teal-mid)" },
    { label: "Specificity", value: score.specificity, color: "var(--blue-mid)" },
    { label: "Clinical Reasoning", value: score.reasoning_quality, color: "var(--purple-mid)" },
    { label: "Safety Coverage", value: score.safety, color: score.safety >= 70 ? "var(--green-mid)" : "var(--red-mid)" },
  ];

  const overallColor = score.overall >= 80 ? "var(--green-mid)" : score.overall >= 60 ? "var(--amber-mid)" : "var(--red-mid)";

  return (
    <div style={{
      background: "var(--bg-subtle)", border: "1px solid var(--border-light)", borderRadius: 8,
      padding: 12, display: "flex", flexDirection: "column", gap: 8,
    }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <span className="section-label">Documentation Quality Score</span>
        <span style={{ fontSize: 20, fontWeight: 800, color: overallColor, fontFamily: "'IBM Plex Mono', monospace" }}>
          {score.overall}
          <span style={{ fontSize: 12, fontWeight: 500, color: "var(--text-muted)" }}>/100</span>
        </span>
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>
        {dims.map(dim => (
          <div key={dim.label} style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <span style={{ fontSize: 10, color: "var(--text-muted)", width: 130, flexShrink: 0 }}>{dim.label}</span>
            <div className="quality-bar-track" style={{ flex: 1 }}>
              <div className="quality-bar-fill" style={{ width: `${dim.value}%`, background: dim.color }} />
            </div>
            <span style={{ fontSize: 10, fontWeight: 600, color: dim.color, width: 28, textAlign: "right", fontFamily: "'IBM Plex Mono', monospace" }}>
              {dim.value}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

export function SOAPPreview({ soapNote, patientData, qualityScore, cleanedTranscript }: SOAPPreviewProps) {
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<"soap" | "transcript">("soap");

  if (!soapNote) {
    return (
      <div style={{
        border: "2px dashed var(--border-light)", borderRadius: 12, padding: 32,
        textAlign: "center", background: "var(--bg-paper)",
      }}>
        <FileText style={{ width: 32, height: 32, color: "var(--border-medium)", margin: "0 auto 10px" }} />
        <p style={{ fontSize: 13, fontWeight: 600, color: "var(--text-muted)", margin: 0 }}>
          Clinical SOAP Documentation Workspace
        </p>
        <p style={{ fontSize: 11, color: "var(--text-placeholder)", marginTop: 4 }}>
          Complete patient intake dictation to generate structured EMR documentation.
        </p>
      </div>
    );
  }

  const handleCopy = () => {
    const text = `CLINICAL SOAP NOTE — CLINICA PLATFORM
Patient: ${patientData?.patient_name ?? "Patient"}  |  Date: ${new Date().toLocaleDateString()}
════════════════════════════════════════

SUBJECTIVE (S):
${soapNote.subjective}

OBJECTIVE (O):
${soapNote.objective}

ASSESSMENT (A):
${soapNote.assessment}

PLAN (P):
${soapNote.plan}

════════════════════════════════════════
Generated by Clinica Clinical Documentation Platform`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => window.print();

  const sections = [
    {
      key: "S", title: "Subjective", fullTitle: "Subjective (S)",
      desc: "HPI, chief complaint, review of systems",
      content: soapNote.subjective,
      icon: <Stethoscope style={{ width: 13, height: 13 }} />,
      color: { bg: "var(--teal-bg)", border: "var(--teal-border)", title: "var(--teal-dark)", label: "#0d9488" },
    },
    {
      key: "O", title: "Objective", fullTitle: "Objective (O)",
      desc: "Vitals, physical exam, special tests",
      content: soapNote.objective,
      icon: <Activity style={{ width: 13, height: 13 }} />,
      color: { bg: "var(--blue-bg)", border: "var(--blue-border)", title: "var(--blue-dark)", label: "#2563eb" },
    },
    {
      key: "A", title: "Assessment", fullTitle: "Assessment (A)",
      desc: "Diagnostic impression, differential, triage context",
      content: soapNote.assessment,
      icon: <ClipboardList style={{ width: 13, height: 13 }} />,
      color: { bg: "var(--purple-bg)", border: "var(--purple-border)", title: "var(--purple-dark)", label: "#9333ea" },
    },
    {
      key: "P", title: "Plan", fullTitle: "Plan (P)",
      desc: "Medications, activity, follow-up, precautions",
      content: soapNote.plan,
      icon: <Calendar style={{ width: 13, height: 13 }} />,
      color: { bg: "var(--green-bg)", border: "var(--green-border)", title: "var(--green-dark)", label: "#16a34a" },
    },
  ];

  return (
    <div className="card" style={{ overflow: "hidden" }}>
      {/* Toolbar */}
      <div style={{
        padding: "10px 14px", borderBottom: "1px solid var(--border-light)",
        background: "var(--bg-subtle)",
        display: "flex", alignItems: "center", justifyContent: "space-between",
        boxShadow: "0 1px 0 rgba(255,255,255,0.8)",
      }}>
        {/* Tabs */}
        <div className="tab-bar">
          <button className={`tab-btn ${activeTab === "soap" ? "active" : ""}`} onClick={() => setActiveTab("soap")}>
            SOAP Note
          </button>
          {cleanedTranscript && (
            <button className={`tab-btn ${activeTab === "transcript" ? "active" : ""}`} onClick={() => setActiveTab("transcript")}>
              Formatted Transcript
            </button>
          )}
        </div>

        {/* Actions */}
        <div style={{ display: "flex", gap: 6 }}>
          <button onClick={handlePrint} className="btn-raised no-print" style={{ display: "flex", alignItems: "center", gap: 5, padding: "5px 10px", fontSize: 11 }}>
            <Printer style={{ width: 12, height: 12 }} /> Print
          </button>
          <button onClick={handleCopy} className="btn-raised" style={{ display: "flex", alignItems: "center", gap: 5, padding: "5px 10px", fontSize: 11 }}>
            {copied
              ? <><Check style={{ width: 12, height: 12, color: "var(--green-mid)" }} /> Copied!</>
              : <><Copy style={{ width: 12, height: 12 }} /> Copy SOAP</>
            }
          </button>
        </div>
      </div>

      {/* Content */}
      <div style={{ padding: 14, display: "flex", flexDirection: "column", gap: 12 }}>
        {qualityScore && <QualityMeter score={qualityScore} />}

        {activeTab === "soap" ? (
          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            {sections.map(sec => (
              <div key={sec.key} style={{
                border: `1px solid ${sec.color.border}`,
                borderRadius: 9, overflow: "hidden",
                boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
              }}>
                {/* Section Header */}
                <div style={{
                  background: sec.color.bg, padding: "7px 12px",
                  borderBottom: `1px solid ${sec.color.border}`,
                  display: "flex", alignItems: "center", gap: 6,
                }}>
                  <span style={{ color: sec.color.label }}>{sec.icon}</span>
                  <span style={{ fontSize: 10, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.08em", color: sec.color.title }}>
                    {sec.fullTitle}
                  </span>
                  <span style={{ fontSize: 9, color: "var(--text-muted)", marginLeft: 2 }}>— {sec.desc}</span>
                </div>
                {/* Section Body */}
                <div style={{ padding: "10px 12px", background: "white" }}>
                  <p style={{
                    fontSize: 12, color: "var(--text-secondary)", margin: 0,
                    lineHeight: 1.7, whiteSpace: "pre-line",
                    fontFamily: "'IBM Plex Mono', monospace",
                  }}>
                    {sec.content}
                  </p>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="inset-panel" style={{ padding: 12 }}>
            <span className="section-label" style={{ display: "block", marginBottom: 8 }}>
              Cleaned & Normalized Transcript Output
            </span>
            <p style={{
              fontSize: 12, color: "var(--text-secondary)", margin: 0,
              lineHeight: 1.7, whiteSpace: "pre-line",
              fontFamily: "'IBM Plex Mono', monospace",
            }}>
              {cleanedTranscript}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
