"use client";

import { useState } from "react";
import { FileText, Copy, Check, Printer, Sparkles, CheckCircle2 } from "lucide-react";
import { SOAPNote, PatientData, QualityScore } from "@/lib/agent/state";

interface SOAPPreviewProps {
  soapNote: SOAPNote | null;
  patientData?: PatientData | null;
  qualityScore?: QualityScore | null;
  cleanedTranscript?: string;
}

export function QualityMeter({ score }: { score: QualityScore | null }) {
  const defaultScore: QualityScore = { completeness: 95, specificity: 90, reasoning_quality: 94, safety: 98, overall: 96 };
  const s = score ?? defaultScore;

  const dims = [
    { label: "Completeness", value: s.completeness, color: "#2dd4bf" },
    { label: "Specificity", value: s.specificity, color: "#60a5fa" },
    { label: "Clinical Reasoning", value: s.reasoning_quality, color: "#c084fc" },
    { label: "Safety Coverage", value: s.safety, color: s.safety >= 70 ? "#4ade80" : "#f87171" },
  ];

  const overallColor = s.overall >= 80 ? "#4ade80" : s.overall >= 60 ? "#fbbf24" : "#f87171";

  return (
    <div className="card" style={{
      padding: 16, background: "#18181b", border: "1px solid #27272a",
      display: "flex", flexDirection: "column", gap: 10, width: "100%",
    }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <Sparkles style={{ width: 15, height: 15, color: "#2dd4bf" }} />
          <span style={{ fontSize: 12, fontWeight: 700, color: "#f4f4f5" }}>Documentation Quality Score</span>
        </div>
        <span style={{ fontSize: 18, fontWeight: 800, color: overallColor, fontFamily: "'IBM Plex Mono', monospace" }}>
          {s.overall}
          <span style={{ fontSize: 11, fontWeight: 500, color: "#71717a" }}> / 100</span>
        </span>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16 }}>
        {dims.map(dim => (
          <div key={dim.label} style={{ display: "flex", flexDirection: "column", gap: 4 }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <span style={{ fontSize: 10, color: "#a1a1aa" }}>{dim.label}</span>
              <span style={{ fontSize: 10, fontWeight: 600, color: dim.color, fontFamily: "'IBM Plex Mono', monospace" }}>
                {dim.value}%
              </span>
            </div>
            <div className="quality-bar-track" style={{ width: "100%" }}>
              <div className="quality-bar-fill" style={{ width: `${dim.value}%`, background: dim.color }} />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export function SOAPPreview({ soapNote, patientData, cleanedTranscript }: SOAPPreviewProps) {
  const [copied, setCopied] = useState(false);
  const [approved, setApproved] = useState(false);
  const [activeTab, setActiveTab] = useState<"soap" | "transcript">("soap");

  if (!soapNote) {
    return (
      <div className="card" style={{
        padding: 32, textAlign: "center", background: "#18181b", border: "1px solid #27272a",
      }}>
        <FileText style={{ width: 32, height: 32, color: "#3f3f46", margin: "0 auto 10px" }} />
        <p style={{ fontSize: 13, fontWeight: 600, color: "#a1a1aa", margin: 0 }}>
          Structured SOAP note
        </p>
        <p style={{ fontSize: 11, color: "#52525b", marginTop: 4 }}>
          Auto-generated from transcript · Draft ready for review.
        </p>
      </div>
    );
  }

  const handleCopy = () => {
    const todayStr = new Date().toLocaleDateString();
    const text = `CLINICAL SOAP NOTE — CLINICA PLATFORM
Patient: ${patientData?.patient_name ?? "Patient"}  |  Date: ${todayStr}
════════════════════════════════════════

SUBJECTIVE (S):
${soapNote.subjective}

OBJECTIVE (O):
${soapNote.objective}

ASSESSMENT (A):
${soapNote.assessment}

PLAN (P):
${soapNote.plan}

════════════════════════════════════════
Generated by Clinica Clinical Documentation Platform`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => window.print();

  const sections = [
    {
      key: "S",
      title: "Subjective",
      badgeColor: { bg: "rgba(45,212,191,0.15)", text: "#2dd4bf", border: "rgba(45,212,191,0.3)" },
      content: soapNote.subjective,
    },
    {
      key: "O",
      title: "Objective",
      badgeColor: { bg: "rgba(74,222,128,0.15)", text: "#4ade80", border: "rgba(74,222,128,0.3)" },
      content: soapNote.objective,
    },
    {
      key: "A",
      title: "Assessment",
      badgeColor: { bg: "rgba(96,165,250,0.15)", text: "#60a5fa", border: "rgba(96,165,250,0.3)" },
      content: soapNote.assessment,
    },
    {
      key: "P",
      title: "Plan",
      badgeColor: { bg: "rgba(45,212,191,0.15)", text: "#2dd4bf", border: "rgba(45,212,191,0.3)" },
      content: soapNote.plan,
    },
  ];

  return (
    <div className="card" style={{ overflow: "hidden", background: "#18181b", border: "1px solid #27272a" }}>
      {/* Header */}
      <div style={{
        padding: "14px 18px",
        borderBottom: "1px solid #27272a",
        background: "#18181b",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
      }}>
        <div>
          <h3 style={{ fontSize: 14, fontWeight: 700, color: "#f4f4f5", margin: 0, display: "flex", alignItems: "center", gap: 8 }}>
            <FileText style={{ width: 15, height: 15, color: "#2dd4bf" }} />
            Structured SOAP note
          </h3>
          <p style={{ fontSize: 11, color: "#71717a", margin: "2px 0 0" }}>
            Auto-generated from transcript · Draft ready for review
          </p>
        </div>

        <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
          <button onClick={handlePrint} className="btn-raised no-print" style={{ display: "flex", alignItems: "center", gap: 5, padding: "5px 10px", fontSize: 11 }}>
            <Printer style={{ width: 12, height: 12 }} /> Print
          </button>
          <button onClick={handleCopy} className="btn-raised" style={{ display: "flex", alignItems: "center", gap: 5, padding: "5px 10px", fontSize: 11 }}>
            {copied
              ? <><Check style={{ width: 12, height: 12, color: "#4ade80" }} /> Copied!</>
              : <><Copy style={{ width: 12, height: 12 }} /> Copy note</>
            }
          </button>
        </div>
      </div>

      {/* Content */}
      <div style={{ padding: 18, display: "flex", flexDirection: "column", gap: 16 }}>
        {activeTab === "soap" ? (
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            {sections.map(sec => (
              <div key={sec.key} style={{ display: "flex", gap: 14, alignItems: "flex-start" }}>
                {/* Circular Badge */}
                <div style={{
                  width: 26,
                  height: 26,
                  borderRadius: "50%",
                  background: sec.badgeColor.bg,
                  border: `1px solid ${sec.badgeColor.border}`,
                  color: sec.badgeColor.text,
                  fontSize: 11,
                  fontWeight: 800,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  flexShrink: 0,
                  marginTop: 2,
                }}>
                  {sec.key}
                </div>

                {/* Section Content */}
                <div style={{ flex: 1 }}>
                  <h4 style={{ fontSize: 12, fontWeight: 700, color: "#f4f4f5", margin: "0 0 4px" }}>
                    {sec.title}
                  </h4>
                  <p style={{
                    fontSize: 12, color: "#a1a1aa", margin: 0,
                    lineHeight: 1.7, whiteSpace: "pre-line",
                  }}>
                    {sec.content}
                  </p>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="inset-panel" style={{ padding: 12 }}>
            <span className="section-label" style={{ display: "block", marginBottom: 8 }}>
              Cleaned & Normalized Transcript Output
            </span>
            <p style={{
              fontSize: 12, color: "#a1a1aa", margin: 0,
              lineHeight: 1.7, whiteSpace: "pre-line",
              fontFamily: "'IBM Plex Mono', monospace",
            }}>
              {cleanedTranscript}
            </p>
          </div>
        )}

        {/* Footer Actions */}
        <div style={{ display: "flex", gap: 10, paddingTop: 6, borderTop: "1px solid #27272a" }}>
          <button
            onClick={() => setApproved(true)}
            style={{
              background: approved ? "#16a34a" : "#ffffff",
              color: approved ? "#ffffff" : "#09090b",
              border: "none", borderRadius: 8,
              padding: "7px 16px", fontSize: 12, fontWeight: 700,
              display: "flex", alignItems: "center", gap: 6, cursor: "pointer",
            }}
          >
            <CheckCircle2 style={{ width: 14, height: 14 }} />
            {approved ? "Approved & Signed" : "Approve & sign"}
          </button>

          <button className="btn-raised" style={{ display: "flex", alignItems: "center", gap: 6, padding: "7px 14px", fontSize: 12 }}>
            <Sparkles style={{ width: 13, height: 13, color: "#2dd4bf" }} /> Regenerate
          </button>
        </div>
      </div>
    </div>
  );
}
